### ISSUE TITLE
Fix inactive page styling

### ISSUE THREAD

**Issue by MarioRodrigues10** [coderdojobraga/shuriken#137]
**Browser and resolution:**
Browser: Google Chrome
Resolution: 1920*1080

When an account isn't activated this is the page displayed. 

![image](https://user-images.githubusercontent.com/93675410/214041663-d5b4ea46-bf08-4030-84d4-287cca27013e.png)

**Comment by RuiL1904** [comment]
This is fixed by #138 🙏🏼
